## Q1

In [1]:
import pandas as pd
import numpy as np
pd.__version__

'3.0.2'

## Q2

In [2]:
df = pd.read_csv('car_fuel_efficiency.csv')

# len(df)
df.shape[0]

9704

## Q3

In [3]:
df['fuel_type'].nunique()

2

## Q4

In [4]:
(df.isnull().sum() > 0).sum()

np.int64(4)

## Q5

In [5]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [6]:
df.groupby('origin').fuel_efficiency_mpg.max()

origin
Asia      23.759123
Europe    25.967222
USA       24.971452
Name: fuel_efficiency_mpg, dtype: float64

## Q6

In [7]:
df['horsepower'].median()

np.float64(149.0)

In [8]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [9]:
# df['horsepower'].value_counts()

df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [10]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])

In [11]:
df['horsepower'].median()

np.float64(152.0)

## Q7

In [12]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,152.0,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [22]:
condition = df['origin'] == 'Asia'

# columns = ['origin', 'model_year', 'vehicle_weight']
columns = ['model_year', 'vehicle_weight']

df.loc[condition, columns].head(7)

    model_year  vehicle_weight
8         2016     2714.219310
12        2010     2783.868974
14        2007     3582.687368
20        2011     2231.808142
21        2016     2659.431451
34        2014     2844.227534
38        2019     3761.994038

In [23]:
X = df.loc[condition, columns].head(7).values
X

array([[2016.        , 2714.21930965],
       [2010.        , 2783.86897424],
       [2007.        , 3582.68736772],
       [2011.        , 2231.8081416 ],
       [2016.        , 2659.43145076],
       [2014.        , 2844.22753389],
       [2019.        , 3761.99403819]])

In [24]:
XT = X.T
XTX = XT.dot(X)

In [25]:
XTXI = np.linalg.inv(XTX)

In [26]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [27]:
w = XTXI.dot(XT).dot(y)

In [28]:
w.sum().round(3)

np.float64(0.519)