## Churn prediction project

In [1]:
import pandas as pd
import numpy as nb
import matplotlib.pyplot as plt

%matplotlib inline

## 3.2 Data preparation

- Download the data, read it with pandas
- Look at the data
- Make column names and values look uniform
- Check if all the columns read correctly
- Check if the churn variable needs any preparation

In [2]:
df = pd.read_csv('telco_customer_churn.csv')

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
# not all colums appear so:
df.head().T

,0,1,2,3,4
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
SeniorCitizen,0,0,0,0,0
Partner,Yes,No,No,No,No
Dependents,No,No,No,No,No
tenure,1,34,2,45,2
PhoneService,No,Yes,Yes,No,Yes
MultipleLines,No phone service,No,No,No phone service,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No
OnlineBackup,Yes,No,Yes,No,No
DeviceProtection,No,Yes,No,Yes,No
TechSupport,No,No,No,Yes,No
StreamingTV,No,No,No,No,No
StreamingMovies,No,No,No,No,No
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
PaperlessBilling,Yes,No,Yes,No,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,No,No,Yes,No,Yes

In [5]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

categorical_columns = list(df.dtypes[df.dtypes == 'str'].index)

for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ', '_')

In [6]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,7033,7034,7035,7036,7037,7038,7039,7040,7041,7042
customerid,7590-vhveg,5575-gnvde,3668-qpybk,7795-cfocw,9237-hqitu,9305-cdskc,1452-kiovk,6713-okomc,7892-pookp,6388-tabgu,...,9767-fflem,0639-tsiqw,8456-qdavc,7750-eyxwz,2569-wgero,6840-resvb,2234-xaduh,4801-jzazl,8361-ltmkd,3186-ajiek
gender,female,male,male,male,female,female,male,female,female,male,...,male,female,male,female,female,male,female,female,male,male
seniorcitizen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
partner,yes,no,no,no,no,no,no,no,yes,no,...,no,no,no,no,no,yes,yes,yes,yes,no
dependents,no,no,no,no,no,no,yes,no,no,yes,...,no,no,no,no,no,yes,yes,yes,no,no
tenure,1,34,2,45,2,8,22,10,28,62,...,38,67,19,12,72,24,72,11,4,66
phoneservice,no,yes,yes,no,yes,yes,yes,no,yes,yes,...,yes,yes,yes,no,yes,yes,yes,no,yes,yes
multiplelines,no_phone_service,no,no,no_phone_service,no,yes,yes,no_phone_service,yes,no,...,no,yes,no,no_phone_service,no,yes,yes,no_phone_service,yes,no
internetservice,dsl,dsl,dsl,dsl,fiber_optic,fiber_optic,fiber_optic,dsl,fiber_optic,dsl,...,fiber_optic,fiber_optic,fiber_optic,dsl,no,dsl,fiber_optic,dsl,fiber_optic,fiber_optic
onlinesecurity,no,yes,yes,yes,no,no,no,yes,no,yes,...,no,yes,no,no,no_internet_service,yes,no,yes,no,yes
onlinebackup,yes,no,yes,no,no,no,yes,no,no,yes,...,no,yes,no,yes,no_internet_service,no,yes,no,no,no
deviceprotection,no,yes,no,yes,no,yes,no,no,yes,no,...,no,yes,no,yes,no_internet_service,yes,yes,no,no,yes
techsupport,no,no,no,yes,no,no,no,no,yes,no,...,no,no,no,yes,no_internet_service,yes,no,no,no,yes
streamingtv,no,no,no,no,no,yes,yes,no,yes,no,...,no,yes,yes,yes,no_internet_service,yes,yes,no,no,yes
streamingmovies,no,no,no,no,no,yes,no,no,yes,no,...,no,no,no,yes,no_internet_service,yes,yes,no,no,yes
contract,month-to-month,one_year,month-to-month,one_year,month-to-month,month-to-month,month-to-month,month-to-month,month-to-month,one_year,...,month-to-month,month-to-month,month-to-month,one_year,two_year,one_year,one_year,month-to-month,month-to-month,two_year
paperlessbilling,yes,no,yes,no,yes,yes,yes,no,yes,no,...,yes,yes,yes,no,yes,yes,yes,yes,yes,yes
paymentmethod,electronic_check,mailed_check,mailed_check,bank_transfer_(automatic),electronic_check,electronic_check,credit_card_(automatic),mailed_check,electronic_check,bank_transfer_(automatic),...,credit_card_(automatic),credit_card_(automatic),bank_transfer_(automatic),electronic_check,bank_transfer_(automatic),mailed_check,credit_card_(automatic),electronic_check,mailed_check,bank_transfer_(automatic)
monthlycharges,29.85,56.95,53.85,42.3,70.7,99.65,89.1,29.75,104.8,56.15,...,69.5,102.95,78.7,60.65,21.15,84.8,103.2,29.6,74.4,105.65
totalcharges,29.85,1889.5,108.15,1840.75,151.65,820.5,1949.4,301.9,3046.05,3487.95,...,2625.25,6886.25,1495.1,743.3,1419.4,1990.5,7362.9,346.45,306.6,6844.5
churn,no,no,yes,no,yes,yes,no,no,yes,no,...,no,yes,no,no,no,no,no,no,yes,no

In [7]:
tc = pd.to_numeric(df.totalcharges, errors='coerce')
tc.isnull().sum()

df.totalcharges = pd.to_numeric(df.totalcharges, errors='coerce')
df.totalcharges = df.totalcharges.fillna(0)

df[tc.isnull()][['totalcharges', 'customerid']]

      totalcharges  customerid
488            0.0  4472-lvygi
753            0.0  3115-czmzd
936            0.0  5709-lvoeq
1082           0.0  4367-nuyao
1340           0.0  1371-dwpaz
3331           0.0  7644-omvmy
3826           0.0  3213-vvolg
4380           0.0  2520-sgtta
5218           0.0  2923-arzlg
6670           0.0  4075-wkniu
6754           0.0  2775-sefee

In [8]:
df.churn = (df.churn == 'yes').astype(int)

## 3.3 Setting up the validation framework

- Perform the train/valid/test split with Scikit-learn

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
train_test_split?

Signature:
train_test_split(
    *arrays,
    test_size=None,
    train_size=None,
    random_state=None,
    shuffle=True,
    stratify=None,
)
Docstring:
Split arrays or matrices into random train and test subsets.

Quick utility that wraps input validation,
``next(ShuffleSplit().split(X, y))``, and application to input data
into a single call for splitting (and optionally subsampling) data into a
one-liner.

Read more in the :ref:`User Guide <cross_validation>`.

Parameters
----------
*arrays : sequence of indexables with same length / shape[0]
    Allowed inputs are lists, numpy arrays, scipy-sparse
    matrices or pandas dataframes.

test_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the proportion
    of the dataset to include in the test split. If int, represents the
    absolute number of test samples. If None, the value is set to the
    complement of the train size. If ``train_size`` is also None, it will
    be set to 0.25.

train_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the
    proportion of the dataset to include in the train split. If
    int, represents the absolute number of train samples. If None,
    the value is automatically set to the complement of the test size.

random_state : int, RandomState instance or None, default=None
    Controls the shuffling applied to the data before applying the split.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.

shuffle : bool, default=True
    Whether or not to shuffle the data before splitting. If shuffle=False
    then stratify must be None.

stratify : array-like, default=None
    If not None, data is split in a stratified fashion, using this as
    the class labels.
    Read more in the :ref:`User Guide <stratification>`.

Returns
-------
splitting : list, length=2 * len(arrays)
    List containing train-test split of inputs.

    .. versionadded:: 0.16
        If the input is sparse, the output will be a
        ``scipy.sparse.csr_matrix``. Else, output type is the same as the
        input type.

Examples
--------
>>> import numpy as np
>>> from sklearn.model_selection import train_test_split
>>> X, y = np.arange(10).reshape((5, 2)), range(5)
>>> X
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
>>> list(y)
[0, 1, 2, 3, 4]

>>> X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)
...
>>> X_train
array([[4, 5],
       [0, 1],
       [6, 7]])
>>> y_train
[2, 0, 3]
>>> X_test
array([[2, 3],
       [8, 9]])
>>> y_test
[1, 4]

>>> train_test_split(y, shuffle=False)
[[0, 1, 2], [3, 4]]

>>> from sklearn import datasets
>>> iris = datasets.load_iris(as_frame=True)
>>> X, y = iris['data'], iris['target']
>>> X.head()
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
>>> y.head()
0    0
1    0
2    0
3    0
4    0
...

>>> X_train, X_test, y_train, y_test = train_test_split(
... X, y, test_size=0.33, random_state=42)
...
>>> X_train.head()
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
96                 5.7               2.9                4.2               1.3
105                7.6               3.0                6.6               2.1
66                 5.6               3.0                4.5               1.5
0                  5.1               3.5                1.4               0.2
122                7.7               2.8                6.7               2.0
>>> y_train.head()
96     1
105    2
66     1
0      0
122    2
...
>>> X_test.head()
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
73                 6.1               2.8                4.7               1.2
18                 5.7               3.8                1.7               0.3
118                7.7               2.6                6.9               2.3
78                 6.0               2.9                4.5               1.5
76                 6.8               2.8                4.8               1.4
>>> y_test.head()
73     1
18     0
118    2
78     1
76     1
...
File:      ~/miniconda3/envs/mzc/lib/python3.12/site-packages/sklearn/model_selection/_split.py
Type:      function

In [11]:
df_full_train, df_test = train_test_split(df, train_size= 0.8, test_size= 0.2, random_state=1)
df_train, df_validation = train_test_split(df_full_train, train_size = 0.75, test_size = 0.25, random_state=1)

In [12]:
len(df_train), len(df_validation), len(df_test)

(4225, 1409, 1409)

In [13]:
df_train = df_train.reset_index(drop=True)
df_validation = df_validation.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = df_train.churn.values
y_validation = df_validation.churn.values
y_test = df_test.churn.values

In [14]:
del df_train['churn']
del df_validation['churn']
del df_test['churn']

## 3.4 EDA

- Check missing values
- Look at the target variable (churn)
- Look at the numerical and categorical variables

In [15]:
df_full_train = df_full_train.reset_index(drop=True)

In [16]:
df_full_train.isnull().sum()

# df_full_train.churn.value_counts()
print(df_full_train.churn.value_counts(normalize=True)) # churn rate
print(df_full_train.churn.mean().round(5))

churn
0    0.730032
1    0.269968
Name: proportion, dtype: float64
0.26997

In [17]:
globel_churn_rate = df_full_train.churn.mean().round(5)

In [18]:
df_full_train.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges', 'churn'],
      dtype='str')

In [19]:
# take numerical features
numerical = ['tenure', 'monthlycharges', 'totalcharges']

# take categorical features
categorical = ['gender', 'seniorcitizen', 'partner', 'dependents',
               'phoneservice', 'multiplelines', 'internetservice',
               'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
               'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
               'paymentmethod']

In [20]:
df_full_train[categorical]
df_full_train[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

## 3.5 Feature Importance: Churn rate & Risk ratio
Feature importance analysis (part of EDA) - identifying which features affect our target variable

- Churn rate
- Risk ratio
- Mutual information - later

In [21]:
df_full_train.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,5442-pptjy,male,0,yes,yes,12,yes,no,no,no_internet_service,...,no_internet_service,no_internet_service,no_internet_service,no_internet_service,two_year,no,mailed_check,19.70,258.35,0
1,6261-rcvns,female,0,no,no,42,yes,no,dsl,yes,...,yes,yes,no,yes,one_year,no,credit_card_(automatic),73.90,3160.55,1
2,2176-osjuv,male,0,yes,no,71,yes,yes,dsl,yes,...,no,yes,no,no,two_year,no,bank_transfer_(automatic),65.15,4681.75,0
3,6161-erdgd,male,0,yes,yes,71,yes,yes,dsl,yes,...,yes,yes,yes,yes,one_year,no,electronic_check,85.45,6300.85,0
4,2364-ufrom,male,0,no,no,30,yes,no,dsl,yes,...,no,yes,yes,no,one_year,no,electronic_check,70.40,2044.75,0

**Churn rate**

In [22]:
globel_churn = df_full_train.churn.mean()

churn_female = df_full_train[df_full_train.gender == 'female'].churn.mean()
churn_male = df_full_train[df_full_train.gender == 'male'].churn.mean()

In [23]:
df_full_train.partner.value_counts()

partner
no     2932
yes    2702
Name: count, dtype: int64

In [24]:
churn_partner = df_full_train[df_full_train.partner == 'yes'].churn.mean()
churn_no_partner = df_full_train[df_full_train.partner == 'no'].churn.mean()

**Risk Difference**

**Global - Group:**
 
- If it is less than 0, more likely to churn.
- Else, if it is greater than 0, less likely to churn.

In [27]:
# as u see the risk difference is tiny, so the gender doesn't really matter in churn

print(globel_churn - churn_female)
print(globel_churn - churn_male)

print("-----------------------------")

# as u see the risk difference is NOT tiny, so if the person has a partner that's really matter in churn

print(globel_churn - churn_partner)
print(globel_churn - churn_no_partner)

# so perhaps the partner variable is more important for prediciting churn than the gender variable, So i want to measure the feature importance

-0.006855983216553063
0.006754520462819769
-----------------------------
0.06493474245795922
-0.05984095297455855

**Risk ratio**

**Risk = (Group / Global)**

- If it's GREATER than 1, it's more likely to churn
- If it's LESS than 1, it's less likely to churn

In [28]:
print(churn_no_partner / globel_churn)
print(churn_partner / globel_churn)

1.2216593879412643
0.7594724924338315

**Risk Difference And Risk ratio, they are very similar, but there's an important difference**

![chur_rate](churn-rate.png)

In [68]:
import duckdb

query = f"""

select gender,
       avg(churn),
       avg(churn) - {globel_churn} as Risk_diff,
       avg(churn) - {globel_churn} as Risk_ratio
       from df_full_train
       group by gender
"""

r = duckdb.query(query).df()

# Or use:
df_group = df_full_train.groupby('gender').churn.agg(['mean', 'count']) # return dataFrame
df_group['risk_diff'] = df_group['mean'] - globel_churn
df_group['risk_ratio'] = df_group['mean'] / globel_churn

df_group

            mean  count  risk_diff  risk_ratio
gender
female  0.276824   2796   0.006856    1.025396
male    0.263214   2838  -0.006755    0.974980

In [78]:
# for add all categoricals variables (apply risk difference and risk ratio

from IPython.display import display ## to print multiple (image, videos, DataFrame in single cell

for c in categorical:

    print(c)
    df_group = df_full_train.groupby(c).churn.agg(['mean', 'count'])
    df_group['risk_diff'] = df_group['mean'] - globel_churn
    df_group['risk_ratio'] = df_group['mean'] / globel_churn
    display(df_group)
    print("\n")

gender

            mean  count  risk_diff  risk_ratio
gender
female  0.276824   2796   0.006856    1.025396
male    0.263214   2838  -0.006755    0.974980

seniorcitizen

                   mean  count  risk_diff  risk_ratio
seniorcitizen
0              0.242270   4722  -0.027698    0.897403
1              0.413377    912   0.143409    1.531208

partner

             mean  count  risk_diff  risk_ratio
partner
no       0.329809   2932   0.059841    1.221659
yes      0.205033   2702  -0.064935    0.759472

dependents

                mean  count  risk_diff  risk_ratio
dependents
no          0.313760   3968   0.043792    1.162212
yes         0.165666   1666  -0.104302    0.613651

phoneservice

                  mean  count  risk_diff  risk_ratio
phoneservice
no            0.241316    547  -0.028652    0.893870
yes           0.273049   5087   0.003081    1.011412

multiplelines

                      mean  count  risk_diff  risk_ratio
multiplelines
no                0.257407   2700  -0.012561    0.953474
no_phone_service  0.241316    547  -0.028652    0.893870
yes               0.290742   2387   0.020773    1.076948

internetservice

                     mean  count  risk_diff  risk_ratio
internetservice
dsl              0.192347   1934  -0.077621    0.712482
fiber_optic      0.425171   2479   0.155203    1.574895
no               0.077805   1221  -0.192163    0.288201

onlinesecurity

                         mean  count  risk_diff  risk_ratio
onlinesecurity
no                   0.420921   2801   0.150953    1.559152
no_internet_service  0.077805   1221  -0.192163    0.288201
yes                  0.153226   1612  -0.116742    0.567570

onlinebackup

                         mean  count  risk_diff  risk_ratio
onlinebackup
no                   0.404323   2498   0.134355    1.497672
no_internet_service  0.077805   1221  -0.192163    0.288201
yes                  0.217232   1915  -0.052736    0.804660

deviceprotection

                         mean  count  risk_diff  risk_ratio
deviceprotection
no                   0.395875   2473   0.125907    1.466379
no_internet_service  0.077805   1221  -0.192163    0.288201
yes                  0.230412   1940  -0.039556    0.853480

techsupport

                         mean  count  risk_diff  risk_ratio
techsupport
no                   0.418914   2781   0.148946    1.551717
no_internet_service  0.077805   1221  -0.192163    0.288201
yes                  0.159926   1632  -0.110042    0.592390

streamingtv

                         mean  count  risk_diff  risk_ratio
streamingtv
no                   0.342832   2246   0.072864    1.269897
no_internet_service  0.077805   1221  -0.192163    0.288201
yes                  0.302723   2167   0.032755    1.121328

streamingmovies

                         mean  count  risk_diff  risk_ratio
streamingmovies
no                   0.338906   2213   0.068938    1.255358
no_internet_service  0.077805   1221  -0.192163    0.288201
yes                  0.307273   2200   0.037305    1.138182

contract

                    mean  count  risk_diff  risk_ratio
contract
month-to-month  0.431701   3104   0.161733    1.599082
one_year        0.120573   1186  -0.149395    0.446621
two_year        0.028274   1344  -0.241694    0.104730

paperlessbilling

                      mean  count  risk_diff  risk_ratio
paperlessbilling
no                0.172071   2313  -0.097897    0.637375
yes               0.338151   3321   0.068183    1.252560

paymentmethod

                               mean  count  risk_diff  risk_ratio
paymentmethod
bank_transfer_(automatic)  0.168171   1219  -0.101797    0.622928
credit_card_(automatic)    0.164339   1217  -0.105630    0.608733
electronic_check           0.455890   1893   0.185922    1.688682
mailed_check               0.193870   1305  -0.076098    0.718121